apiVersion: v1
kind: Service
metadata:
  name: userproductmonolith-service
spec:
  selector:
    app: userproductmonolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  type: NodePort